"""add_cwe_owasp_to_issues

Revision ID: 56c463a0a97d
Revises: f1d3a9b7c221
Create Date: 2026-04-22 15:58:00.427977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c463a0a97d'
down_revision = 'f1d3a9b7c221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dast_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cwe', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('owasp', sa.String(length=128), nullable=True))

    with op.batch_alter_table('sast_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cwe', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('owasp', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sast_issues', schema=None) as batch_op:
        batch_op.drop_column('owasp')
        batch_op.drop_column('cwe')

    with op.batch_alter_table('dast_issues', schema=None) as batch_op:
        batch_op.drop_column('owasp')
        batch_op.drop_column('cwe')

    # ### end Alembic commands ###
